---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  scan_write_creds:
    file: ./src/secrets/scan_write_creds.yml

services:
  saver:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    image: khulnasoft/saver
    init: true
    restart: "no"
    secrets:
      - source: scan_write_creds
        target: scan_write_creds.yml
  redis:
    image: redis:alpine
